[project]
name = 'stacks-jackpot-wall'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.jackpot-wall]
path = 'contracts/jackpot-wall.clar'
clarity_version = 2
epoch = 'latest'

[contracts.passkey-vault]
path = 'contracts/passkey-vault.clar'
clarity_version = 2
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
